#!/bin/bash
# Run from geometricVofExt top-level directory only
cd "${0%/*}" || exit
wmake -check-dir "$WM_PROJECT_USER_DIR/modules/geometricVofExt" 2>/dev/null || {
    echo "Error (${0##*/}) : not located in \$WM_PROJECT_USER_DIR/modules/geometricVofExt"
    echo "    Check your OpenFOAM environment and installation"
    exit 1
}
#------------------------------------------------------------------------------

echo
echo "*********** Compile CGAL with GMP and MPFR Using System GCC ************"
echo

# Modify $WM_PROJECT_DIR/etc/config.sh/compiler
[ -f $WM_PROJECT_DIR/etc/config.sh/compiler_backup ] || cp $WM_PROJECT_DIR/etc/config.sh/compiler $WM_PROJECT_DIR/etc/config.sh/compiler_backup

awk '
    BEGIN {
        in_section = 0
    }
    /case "\$WM_COMPILER_TYPE" in/ {
        print "" $0
        print "system)"
        print "    gmp_version=gmp-6.2.1"
        print "    mpfr_version=mpfr-4.1.0"
        print "    mpc_version=mpc-1.2.1"
        print "    gsl_version=gsl-2.7.1    # used by waves2Foam"
        print "    ;;"

        in_section = 1
        next
    }
    /ThirdParty)/ && in_section {
        print
        in_section = 0
        next
    }
    !in_section {
        print
    }
' $WM_PROJECT_DIR/etc/config.sh/compiler_backup > $WM_PROJECT_DIR/etc/config.sh/compiler


# Modify $WM_PROJECT_DIR/etc/config.sh/settings
[ -f $WM_PROJECT_DIR/etc/config.sh/settings_backup ] || cp $WM_PROJECT_DIR/etc/config.sh/settings $WM_PROJECT_DIR/etc/config.sh/settings_backup

awk '
    BEGIN {
        in_section = 0
    }
    /case "\$WM_COMPILER_TYPE-\$WM_COMPILER" in/ {
        print "" $0
        print "system-Gcc)"
        print "    gmpDir=\"$archDir/${gmp_version}\""
        print "    mpfrDir=\"$archDir/${mpfr_version}\""
        print "    mpcDir=\"$archDir/${mpc_version}\""
        print "    gslDir=\"$archDir/${gsl_version}\"    # used by waves2Foam"
        print "    _foamAddLibAuto \"$gmpDir\" && export GMP_ARCH_PATH=\"$gmpDir\""
        print "    _foamAddLibAuto \"$mpfrDir\" && export MPFR_ARCH_PATH=\"$mpfrDir\""
        print "    _foamAddLibAuto \"$mpcDir\""
        print "    _foamAddLibAuto \"$gslDir\""
        print "    ;;"

        in_section = 1
        next
    }
    /ThirdParty-Gcc\*)/ && in_section {
        print
        in_section = 0
        next
    }
    !in_section {
        print
    }
' $WM_PROJECT_DIR/etc/config.sh/settings_backup > $WM_PROJECT_DIR/etc/config.sh/settings


# Renew env of OpenFOAM
source $WM_PROJECT_DIR/etc/bashrc


cd $WM_THIRD_PARTY_DIR


# Download and unpack GMP, MPFR and MPC
[ -f gmp-6.2.1.tar.xz ] || wget -nv https://gmplib.org/download/gmp/gmp-6.2.1.tar.xz --no-check-certificate
[ -d gmp-6.2.1 ] || tar -xf gmp-6.2.1.tar.xz

[ -f mpfr-4.1.0.tar.gz ] || wget -nv https://ftp.gnu.org/gnu/mpfr/mpfr-4.1.0.tar.gz --no-check-certificate
[ -d mpfr-4.1.0 ] || tar -xzf mpfr-4.1.0.tar.gz

[ -f mpc-1.2.1.tar.gz ] || wget -nv https://ftp.gnu.org/gnu/mpc/mpc-1.2.1.tar.gz --no-check-certificate
[ -d mpc-1.2.1 ] || tar -xzf mpc-1.2.1.tar.gz


# Remove old build
rm -rf ./build/$WM_ARCH/gmp-6.2.1
rm -rf ./build/$WM_ARCH/mpc-1.2.1
rm -rf ./build/$WM_ARCH/mpfr-4.1.0

rm -rf ./platforms/$WM_ARCH/gmp-6.2.1
rm -rf ./platforms/$WM_ARCH/mpc-1.2.1
rm -rf ./platforms/$WM_ARCH/mpfr-4.1.0

rm -rf ./build/$WM_ARCH$WM_COMPILER/CGAL-*

rm -rf ./platforms/$WM_ARCH$WM_COMPILER/boost_*
rm -rf ./platforms/$WM_ARCH$WM_COMPILER/CGAL-*


# Build
./makeGcc gcc-system gmp-6.2.1 mpfr-4.1.0 mpc-1.2.1
./makeCGAL -with-lib gmp-6.2.1 mpfr-4.1.0

echo
echo "********************************* Done *********************************"
echo

#------------------------------------------------------------------------------