#!/bin/sh
cd "${0%/*}" || exit    # Run from this directory
#------------------------------------------------------------------------------

wclean -all test

wclean -all utilities

wclean -all solvers

#------------------------------------------------------------------------------
