#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

[ -d postProcessing ] || mkdir postProcessing

calcSurfaceMeshNonUniformFlow initialShapeMeshIcosphere.stlb -dt 0.005 \
    > log.calcSurfaceMeshNonUniformFlow_initialShapeMeshIcosphere

calcSurfaceMeshNonUniformFlow initialShapeMeshNonUniform.stlb -dt 0.005 \
    > log.calcSurfaceMeshNonUniformFlow_initialShapeMeshNonUniform

#------------------------------------------------------------------------------
