#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

runApplication blockMesh
runApplication surfaceFeatureExtract
runApplication snappyHexMesh -overwrite
runApplication checkMesh

runApplication setVofField -np 8

runApplication decomposePar -fileHandler collated

runParallel $(getApplication) -fileHandler collated

writeVtkSeries plicInterface
writeVtkSeries isoInterface
writeVtkSeries walls

touch ${PWD##*/}.foam

#------------------------------------------------------------------------------
