#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

runApplication blockMesh

runApplication topoSet
runApplication setsToZones -noFlipMap
runApplication createBaffles -overwrite

runApplication setWaveParameters
runApplication setWaveField

runApplication $(getApplication)

writeVtkSeries plicInterface
writeVtkSeries isoInterface
writeVtkSeries walls
writeVtkSeries sides

touch ${PWD##*/}.foam
