#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase0

rm -f constant/cellInterpolationWeight

rm -rf *.foam *.vtp.series

#------------------------------------------------------------------------------
