#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
#------------------------------------------------------------------------------

rm -rf meshIndependence interPlicPhaseChangeFoam interPhaseChangeFoam plots

#------------------------------------------------------------------------------
